### ISSUE TITLE
Add support for |> operator

### ISSUE THREAD

**Issue by raghavjain3** [tree-sitter/tree-sitter-javascript#220] opened 2022-04-21 22:40 UTC
Adding https://tc39.es/proposal-pipeline-operator/ support - thank you!

**Comment by mjambon** [comment] 2022-04-22 00:03
It's duplicate of https://github.com/tree-sitter/tree-sitter-javascript/issues/125
I'll add fresh details there.

**Closed by mjambon** 2022-04-22 00:03 UTC
Labels: duplicate
